services:
  esphome:
    image: ghcr.io/esphome/esphome:latest
    container_name: esphome
    network_mode: host
    privileged: true
    volumes:
      - ./esphome_data:/config
      - /etc/localtime:/etc/localtime:ro
    #   - ./esphome_build:/build # Path for building ESPHome firmware

    # environment:
    #   - ESPHOME_BUILD_PATH=/build
