esphome:
  name: __DEVICE_NAME__
  friendly_name: __DEVICE_NAME__

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# ---- Základní komponenty ----

logger:

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # fallback AP pro první nahrání / debug
  ap:
    ssid: "__DEVICE_NAME__-fallback"
    password: "esphome123"

captive_portal:

# ---- Volitelné / rozšiřitelné ----
# packages:
#   hardware: !include blocks/hardware.yaml
#   sensors: !include blocks/sensors.yaml
#   services: !include blocks/services.yaml
